requirements/base.txt, setup.py, timon/probes.py, timon/scripts/cert_check.py
checks validity of cert with hard coded warning threshold
=> create a cert_check probe

timon/webclient/webif1/src/components/Timon.vue
Use browser `Notifcation` API to notify if state change from "OK" to anything but "OK".
Notification is trigger by refreshing state so with refresh / auto refresh.
=> Front notification

timon/webclient/webif1/.eslintrc, timon/webclient/webif1/src/components/Timon.vue
=> update eslint config + remove empty func

timon/webclient/webif1/package.json
attempt to get rid of some security warnings
=> attempt to update some npm deps

timon/probes.py
env vars can be used to specify how many threads / process / network connections timon shall use in parallel
=> resource limits can be changed via env vars

timon/webclient/webif1/src/components/Timon.vue
linter shoukld have no more errors
=> Fix lint of timon.vue

timon/webclient/webif1/src/components/Timon.vue
=> rmv to accidentally added lines of a future MR

.gitignore, timon/bld_commands.py, timon/webclient/webif1/build.bash
more robust build / for webif.
- symlinks will igored and kept in build dir timin/data/www/webif1
=> fix / improve timon_build scripts for webif comp

timon/webclient/webif1/src/components/Timon.vue
Webif raised errors if a host was not in the minemap.
Code is now more robust. (but still logs these incidents)
Also remove (comment) some logs
=> webif1: rmv some logs. make more robust

CHANGELOG.md, setup.py
just bump version prior to creating first pypi release
=> bump version for new release

setup.py
next version shall properly display some more urls on the pypi page
(e.g. project url / issues url)
=> fix metadata for setup / pypi

.gitlab-ci.yml, .travis.yml, timon/notifiers/postrequest.py, timon/runner.py
CI fails. there are cd commands to enter sub dirs, but command to exit sub dir was missing.
Due to flake update some lines had to be flake cleaned as well
=> fix CI runs (cd in and out of subdir)

timon/webclient/webif1/package.json
=> Dev/feenes/dependabot/npm and yarn/browserify hmr 0.4.1

requirements/base.txt
=> add openssl to requirements

requirements/base.txt
=> Bump version to 0.3.1 (prepare new release)

README.rst
=> add minor doc changes

setup.py, timon/commands.py, timon/config.py, timon/configure.py, timon/probes.py, timon/report_status.py, timon/resources.py, timon/state.py
refactor resource handling into separate module
also remove a few "from __future__" imports
=> refactoring of timon resources

timon/run.py
now a single probe can be run for debugging
=> fix timon run <probename>

timon/webclient/webif1/src/components/Timon.vue
add worst status counter in table header
+
refactoring of  functions to avoid reading all probe infos for each operations (like reading only the result of one probe)
=> Add error counter + refactoring

.github/workflows/build.yml, .github/workflows/scheduled.yml, setup.py
bump version prepare a new release
also run tests for py 3.9 3.10
=> bump version

timon/scripts/clientca_check.py
client_ca_check works now also for servers, that have TLS.13 enabled but also older versions.
Hope to find later a fix, that will also work for servers, that require >= TLS1.3
=> fix: clientcacheck with TLS1.3

timon/plugins/http_server/views.py, timon/plugins/timon_httpsrv.py
There was a bug with the stop of http plugin server
=> FIX STOP plugin http_srv
